### ISSUE TITLE
Issue with connecting - group settings not accessible.

### ISSUE THREAD

**Issue by themak1985** [greenleafadvancement/org.civicrm.googlegroups#3]
Any idea why this is happening? Is this a setting on the Google side I have to change?
I am able to connect successfully,  but when I try to access group settings I get:

Network Error
Unable to reach the server. Please refresh this page in your browser and try again.

This is the error via developer tools.
Is this a wordpress issue?

```
Access to XMLHttpRequest at 'https://accounts.google.com/o/oauth2/auth?response_type=code&access_type=offline&client_id=REDACTED&redirect_uri=https%3A%2F%2Ftarabnyc.org%2Fwp-admin%2Fadmin.php%3Fpage%3DCiviCRM%26q%3Dcivicrm%252Fgooglegroups%252Fsettings%26reset%3D1&state&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.group&approval_prompt=auto' (redirected from 'https://tarabnyc.org/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fgroup&reset=1&action=update&id=14&snippet=json') from origin 'https://tarabnyc.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
jquery.min.js:4 
```

`GET https://accounts.google.com/o/oauth2/auth?response_type=code&access_type=offline&client_id=REDACTED&redirect_uri=https%3A%2F%2Ftarabnyc.org%2Fwp-admin%2Fadmin.php%3Fpage%3DCiviCRM%26q%3Dcivicrm%252Fgooglegroups%252Fsettings%26reset%3D1&state&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.group&approval_prompt=auto net::ERR_FAILED`

**Comment by andyburnsco** [comment]
@themak1985, did you resolve this?

**Comment by themak1985** [comment]
@andyburnsco nope.

**Comment by mark-rodgers** [comment]
Just installed this extension and I have the same issue when trying to access the settings page for a group. Running CiviCRM 5.26.2 on Drupal 7.72

**Comment by mark-rodgers** [comment]
I was previously using [uk.co.vedaconsulting.googlegroup](/veda-consulting-company/uk.co.vedaconsulting.googlegroup). I switched to this extension after noticing issues in CiviCRM 5.x. When I installed [org.civicrm.googlegroups](/greenleafadvancement/org.civicrm.googlegroups), I re-used the same OAuth credentials I had previously been using for [uk.co.vedaconsulting.googlegroup](/veda-consulting-company/uk.co.vedaconsulting.googlegroup).

The Google API docs mention that they only return a refresh token the first time you authorize an application with your OAuth credentials when using offline access ([org.civicrm.googlegroups](/greenleafadvancement/org.civicrm.googlegroups) uses offline access). When you submit the CiviCRM GoogleGroups settings form, it responds with "Connection with Google was successfully authorized.". However, this set of OAuth credentials had already been authorized before, so Google didn't return a refresh token. This refresh token is needed for subsequent Google API requests.

When you visit the settings form of a CiviCRM group there is a [buildForm hook](/greenleafadvancement/org.civicrm.googlegroups/blob/master/googlegroups.php#L210) that makes an API request to fetch a list of Google Groups. This request is failing because the refresh token is missing, causing the form to to break during build.

https://developers.google.com/identity/protocols/oauth2/web-server

![image](https://user-images.githubusercontent.com/2798202/92023668-edea3e80-ed11-11ea-82fd-c0a8cf7f22ce.png)

**Steps to resolve:**

1) [Create a new set of OAuth credentials](https://console.developers.google.com)
2) Go to /civicrm/googlegroups/settings?reset=1
3) Enter credentials and reauthorize

**Side note:**

When the refresh token was missing I noticed the submit button on CiviCRM GoogleGroups settings form previously said "Authorize". Whenever I resubmit the form I'd get redirected to google to reauthorize, then redirected back to CiviCRM settings page with the response "Connection with Google was successfully authorized.".

Now that I've created fresh OAuth credentials and reauthorized, the submit button on CiviCRM GoogleGroups settings form says "Re-authorize if Required". Whenever I resubmit the form now, CiviCRM just responds with "Already authorized.".

**Comment by guyiac** [comment]
I believe we've been doing some work on this extension around deprecated libraries. Let me check with our devs and get back to you.

**Comment by mark-rodgers** [comment]
@guyiac that is not related to this issue, however I did notice that as well. I just created a pull request fixing that issue and gets contacts syncing again.

PR: https://github.com/greenleafadvancement/org.civicrm.googlegroups/pull/8

"Global HTTP Batch endpoint is deprecated. See https://g.co/cloud/global-batch-deprecation for info and migration steps."

**Comment by guyiac** [comment]
OK, Deepak is in London but I'll leave him a message to take a look at it as soon as he gets a chance.

**Comment by deepak-srivastava** [comment]
@mark-rodgers PR #8 has been merged. Thanks for that.
There has also been some improvements to be able to detect the connection status better and allow regenerating refresh token by using prompt('consent').
If you could test latest code from master branch that would be great.

@themak1985 could you try the latest codebase from mater branch and regenerate refresh token from the settings screen, and see if that works.

**Comment by deepak-srivastava** [comment]
UPDATE: v2.1 has been released.

**Comment by deepak-srivastava** [comment]
@themak1985 Please try latest v2.1 and re-open if the problem continue to exist.
